name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependecies
        uses: VaultVulp/action-pipenv@v2.0.1
        with:
          command: sync --dev
      - name: Update setup.py's dependencies
        uses: VaultVulp/action-pipenv@v2.0.1
        with:
          command: run pipenv-setup sync --pipfile
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v3
        with:
          extra_plugins: |
            @semantic-release/exec
            @semantic-release/git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
