name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup python version
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install pipenv
        run: pip install --user pipenv
      - name: Install dependecies
        run: pipenv sync --dev
      - name: Update setup.py's dependencies
        run: pipenv run pipenv-setup sync --pipfile
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        with:
          extra_plugins: |
            @semantic-release/exec
            @semantic-release/git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
